ticketing/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls)
]

# Index page
urlpatterns += [
    path('', views.HomePage.as_view(), name = 'home')
]

# Django site authentication urls
urlpatterns += [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('registration.backends.default.urls'))
]

# Student urls
urlpatterns += [
    path('student/', include('student.urls'))
]

# Worker urls
urlpatterns += [
    path('worker/', include('worker.urls'))
]

# Comment urls
urlpatterns += [
    path('comments/', include('comments.urls'))
]

worker/urls.py
from django.urls import path
from . import views

app_name = 'worker'

urlpatterns = [
	path('update_status/<int:pk>/', views.UpdateStatusView.as_view(), name='update_status'),
	path('all_complaints/', views.ComplaintListView.as_view(), name='all_complaints')
]

worker/models.py
from django.db import models

# Create your models here.

worker/views.py
from django.contrib.auth import get_user_model
User = get_user_model()
from django.views.generic import ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import Http404
from django.urls import reverse_lazy
from student import models

# Create your views here.

class UpdateStatusView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	fields = ['status']
	model = models.Complaint
	template_name = 'worker/update_status.html'
	success_url = reverse_lazy('worker:all_complaints')

	def test_func(self):
		return self.request.user.account_type.all()[0].type == self.get_object().type

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.save()

		return super().form_valid(form)

class ComplaintListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
	model = models.Complaint
	template_name = 'worker/complaint_list.html'

	def test_func(self):
		return self.request.user.account_type.all()[0].type != 'STU'

	def get_queryset(self):
		try:
			self.all_complaints = models.Complaint.objects.filter(type=self.request.user.account_type.all()[0].type)
		except:
			raise Http404

		return self.all_complaints

templates/worker/complaint_list.html
{% extends 'base.html' %}

{% block content %}
	<h1>All complaints</h1>
	<table id="table" class="table-light table-bordered display nowrap" style="width:100%">
		<thead class="alert-light">
			<tr>
				<th>Created at</th>
				<th>Block number</th>
				<th>Room number</th>
				<th>Hall</th>
				<th>Type</th>
				<th>Message</th>
				<th>Status</th>
				<th>Update status</th>
			</tr>
		</thead>
		<tbody>
			{% for complaint in complaint_list %}
				<tr>
					<td>{{ complaint.created_at }}</td>
					<td>{{ complaint.block_number }}</td>
					<td>{{ complaint.room_number }}</td>
					<td>{{ complaint.hall }}</td>
					<td>{{ complaint.type }}</td>
					<td>{{ complaint.message }}</td>
					<td>{{ complaint.status }}</td>
					<td style="text-align:center">
						<a href="{% url 'worker:update_status' pk=complaint.pk %}"><i class="fa fa-pencil-square fa-lg"></i></a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/worker/update_status.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>Update status</h1>
	<form method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<input type='submit' class='btn btn-primary' value='Update' />
		{% endbuttons %}
	</form>
{% endblock %}