comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
	path('create_comment/<int:pk>/', views.CommentCreateView.as_view(), name='create_comment'),
	path('list_comment/', views.CommentListView.as_view(), name='list_comment'),
	path('update_comment/<int:pk>/', views.CommentUpdateView.as_view(), name='update_comment'),
	path('delete_comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='delete_comment')
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
	path('create_complaint/', views.CreateComplaintView.as_view(), name='create_complaint'),
	path('update_complaint/<int:pk>/', views.UpdateComplaintView.as_view(), name='update_complaint'),
	path('detail_complaint/<int:pk>/', views.DetailComplaintView.as_view(), name='detail_complaint'),
	path('delete_complaint/<int:pk>/delete/', views.DeleteComplaintView.as_view(), name='delete_complaint'),
	path('status/', views.StatusView.as_view(), name='status')
]

ticketing/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls)
]

# Index page
urlpatterns += [
    path('', views.HomePage.as_view(), name = 'home')
]

# Django site authentication urls
urlpatterns += [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('registration.backends.default.urls'))
]

# Student urls
urlpatterns += [
    path('student/', include('student.urls'))
]

# Worker urls
urlpatterns += [
    path('worker/', include('worker.urls'))
]

# Comment urls
urlpatterns += [
    path('comments/', include('comments.urls'))
]

worker/urls.py
from django.urls import path
from . import views

app_name = 'worker'

urlpatterns = [
	path('update_status/<int:pk>/', views.UpdateStatusView.as_view(), name='update_status'),
	path('all_complaints/', views.ComplaintListView.as_view(), name='all_complaints')
]

student/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
import misaka

# Create your models here.

class Complaint(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='complaints')
	created_at = models.DateTimeField(auto_now_add=True)
	message = models.TextField()
	message_html = models.TextField(editable=False)

	categories = (
		('ELE', 'Electrical'),
		('PLU', 'Plumbing'),
		('GLA', 'Glass'),
		('CAR', 'Wood')
	)

	halls = (
		('MV', 'MV Hall'),
		('GDB', 'GDB Hall'),
		('DBA', 'DBA Hall'),
		('MSS', 'MSS Hall'),
		('VS', 'VS Hall'),
		('SD', 'SD Hall'),
		('HB', 'HB Hall'),
		('SSB', 'SSB Hall'),
		('KMS', 'KMS Hall'),
		('CVR', 'CVR Hall')
	)

	statuses = (
		('PEN', 'Pending'),
		('PRO', 'In progress'),
		('COM', 'Finished')
	)

	block = (
		('A', 'A'),
		('B', 'B'),
		('C', 'C'),
		('D', 'D')
	)

	type = models.CharField(max_length=3, choices=categories)
	hall = models.CharField(max_length=3, choices=halls)
	status = models.CharField(max_length=3, choices=statuses, default='PEN')
	block_number = models.CharField(max_length=1, choices=block)
	room_number = models.CharField(max_length=3)
	roll_number = models.CharField(max_length=9)

	def save(self, *args, **kwargs):
		self.message_html = misaka.html(self.message)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.message

	class Meta:
		ordering = ['-created_at']

student/views.py
from django.contrib.auth import get_user_model
User = get_user_model()
from django.http import Http404
from django.views.generic import CreateView, DeleteView, UpdateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from . import models

# Create your views here.

class CreateComplaintView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
	fields = ['block_number', 'room_number', 'hall', 'roll_number', 'type', 'message']
	model = models.Complaint
	template_name = 'student/create_complaint.html'
	success_url = reverse_lazy('student:status')

	def test_func(self):
		return self.request.user.account_type.all()[0].type == 'STU'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.user = self.request.user
		self.object.save()

		return super().form_valid(form)

class UpdateComplaintView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	fields = ['block_number', 'room_number', 'hall', 'roll_number', 'type', 'message']
	model = models.Complaint
	template_name = 'student/update_complaint.html'
	success_url = reverse_lazy('student:status')

	def test_func(self):
		return self.request.user.account_type.all()[0].type == 'STU' and self.get_object().user == self.request.user

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.user = self.request.user
		self.object.save()

		return super().form_valid(form)

class DetailComplaintView(LoginRequiredMixin, DetailView):
	model = models.Complaint
	template_name = 'student/detail_complaint.html'

class DeleteComplaintView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = models.Complaint
	template_name = 'student/delete_complaint.html'
	success_url = reverse_lazy('student:status')

	def test_func(self):
		return self.request.user.account_type.all()[0].type == 'STU' and self.get_object().user == self.request.user

class StatusView(LoginRequiredMixin, UserPassesTestMixin, ListView):
	model = models.Complaint
	template_name = 'student/status.html'

	def test_func(self):
		return self.request.user.account_type.all()[0].type == 'STU'

	def get_queryset(self):
		try:
			self.user_complaints = User.objects.prefetch_related('complaints').get(username=self.request.user.username)
		except User.DoesNotExist:
			raise Http404

		return self.user_complaints.complaints.all()

templates/student/create_complaint.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>Create complaint</h1>
	<form method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<input type='submit' class='btn btn-primary' value='Create' />
		{% endbuttons %}
	</form>
{% endblock %}

templates/student/delete_complaint.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>Delete complaint for sure?</h1>
	<form method='post'>
		{% csrf_token %}
		{% buttons %}
			<input type='submit' class='btn btn-danger' value='Delete' />
			<a href="{% url 'student:status' %}" class="btn btn-success">Cancel</a>
		{% endbuttons %}
	</form>
{% endblock %}

templates/student/detail_complaint.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>Complaint details</h1>
	<h5>{{ complaint.message | linebreaks}}</h5>
	<hr>
	<h3>Comments</h3>
	<table id="table" class="table-light table-bordered display nowrap" style="width:100%">
		<thead class="alert-light">
			<tr>
				<th>Created at</th>
				<th>Message</th>
			</tr>
		</thead>
		<tbody>
			{% for comment in complaint.comments.all %}
				<tr>
					<td>{{ comment.created_at }}</td>
					<td>{{ comment.message }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	{% buttons %}
		<button type='button' class='btn btn-primary' onclick="location.href='{% url 'comments:create_comment' pk=complaint.pk %}'">Create comment</button>
	{% endbuttons %}
{% endblock %}

templates/student/status.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>History</h1>
	<table id="table" class="table-light table-bordered display nowrap" style="width:100%">
		<thead class="alert-light">
			<tr>
				<th>Created at</th>
				<th>Block number</th>
				<th>Room number</th>
				<th>Hall</th>
				<th>Type</th>
				<th>Message</th>
				<th>Status</th>
				<th>Edit/Delete</th>
			</tr>
		</thead>
		<tbody>
			{% for complaint in complaint_list %}
				<tr>
					<td>{{ complaint.created_at }}</td>
					<td>{{ complaint.block_number }}</td>
					<td>{{ complaint.room_number }}</td>
					<td>{{ complaint.hall }}</td>
					<td>{{ complaint.type }}</td>
					<td>{{ complaint.message }}</td>
					<td>{{ complaint.status }}</td>
					<td style="text-align:center">
						<a href="{% url 'student:update_complaint' pk=complaint.pk %}"><i class="fas fa-edit"></i></a>
						<a href="{% url 'student:delete_complaint' pk=complaint.pk %}"><i class="fas fa-trash"></i></a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/student/update_complaint.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>Update complaint</h1>
	<form method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<input type='submit' class='btn btn-danger' value='Update' />
		{% endbuttons %}
	</form>
{% endblock %}