comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
	path('create_comment/<int:pk>/', views.CommentCreateView.as_view(), name='create_comment'),
	path('list_comment/', views.CommentListView.as_view(), name='list_comment'),
	path('update_comment/<int:pk>/', views.CommentUpdateView.as_view(), name='update_comment'),
	path('delete_comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='delete_comment')
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
	path('create_complaint/', views.CreateComplaintView.as_view(), name='create_complaint'),
	path('update_complaint/<int:pk>/', views.UpdateComplaintView.as_view(), name='update_complaint'),
	path('detail_complaint/<int:pk>/', views.DetailComplaintView.as_view(), name='detail_complaint'),
	path('delete_complaint/<int:pk>/delete/', views.DeleteComplaintView.as_view(), name='delete_complaint'),
	path('status/', views.StatusView.as_view(), name='status')
]

ticketing/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls)
]

# Index page
urlpatterns += [
    path('', views.HomePage.as_view(), name = 'home')
]

# Django site authentication urls
urlpatterns += [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('registration.backends.default.urls'))
]

# Student urls
urlpatterns += [
    path('student/', include('student.urls'))
]

# Worker urls
urlpatterns += [
    path('worker/', include('worker.urls'))
]

# Comment urls
urlpatterns += [
    path('comments/', include('comments.urls'))
]

worker/urls.py
from django.urls import path
from . import views

app_name = 'worker'

urlpatterns = [
	path('update_status/<int:pk>/', views.UpdateStatusView.as_view(), name='update_status'),
	path('all_complaints/', views.ComplaintListView.as_view(), name='all_complaints')
]

student/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
import misaka

# Create your models here.

class Complaint(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='complaints')
	created_at = models.DateTimeField(auto_now_add=True)
	message = models.TextField()
	message_html = models.TextField(editable=False)

	categories = (
		('ELE', 'Electrical'),
		('PLU', 'Plumbing'),
		('GLA', 'Glass'),
		('CAR', 'Wood')
	)

	halls = (
		('MV', 'MV Hall'),
		('GDB', 'GDB Hall'),
		('DBA', 'DBA Hall'),
		('MSS', 'MSS Hall'),
		('VS', 'VS Hall'),
		('SD', 'SD Hall'),
		('HB', 'HB Hall'),
		('SSB', 'SSB Hall'),
		('KMS', 'KMS Hall'),
		('CVR', 'CVR Hall')
	)

	statuses = (
		('PEN', 'Pending'),
		('PRO', 'In progress'),
		('COM', 'Finished')
	)

	block = (
		('A', 'A'),
		('B', 'B'),
		('C', 'C'),
		('D', 'D')
	)

	type = models.CharField(max_length=3, choices=categories)
	hall = models.CharField(max_length=3, choices=halls)
	status = models.CharField(max_length=3, choices=statuses, default='PEN')
	block_number = models.CharField(max_length=1, choices=block)
	room_number = models.CharField(max_length=3)
	roll_number = models.CharField(max_length=9)

	def save(self, *args, **kwargs):
		self.message_html = misaka.html(self.message)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.message

	class Meta:
		ordering = ['-created_at']

templates/base.html
<!DOCTYPE html>

{% load static %}

{% load activeurl %}

<html>
	<head>
        <meta charset="utf-8">

        <title>Complaints Portal</title>

		<link rel="stylesheet" href="https://bootswatch.com/4/flatly/bootstrap.min.css">

        <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">

        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
			<a class="navbar-brand">Complaints Portal</a>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			{% activeurl %}
				<div class="collapse navbar-collapse" id="navbarColor01">
					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="{% url 'home' %}">Home</a>
						</li>
						{% if user.is_authenticated %}
							{% for type in user.account_type.all %}
								{% if type.type == "STU" %}
									<li class="nav-item">
										<a class="nav-link" href="{% url 'student:create_complaint' %}">Complaints</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" href="{% url 'student:status' %}">Status</a>
									</li>
								{% else %}
									<li class="nav-item">
										<a class="nav-link" href="{% url 'worker:all_complaints' %}">View</a>
									</li>
								{% endif %}
							{% endfor %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'comments:list_comment' %}">Comments</a>
							</li>
						{% endif %}
					</ul>

					<ul class="navbar-nav ml-auto">
						{% if user.is_authenticated %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'auth_logout' %}">Logout</a>
							</li>
						{% else %}
							<li class="nav-item">
								<a class="nav-link" href="{% url 'registration_register' %}">Register</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="{% url 'auth_login' %}">Login</a>
							</li>
						{% endif %}
					</ul>
				</div>
			{% endactiveurl %}
		</nav>

		<div class='container'>
			{% block content %}
			{% endblock %}
		</div>
	</body>

	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
	<script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
	<script src="https://kit.fontawesome.com/ef886b06c1.js" crossorigin="anonymous"></script>
	<script src="{% static '.js/dataTables.js' %}"></script>
</html>

templates/index.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>All complaints</h1>
	<table id="table" class="table-light table-bordered display nowrap" style='width:100%'>
		<thead class="alert-light">
			<tr>
				<th>Created at</th>
				<th>Hall</th>
				<th>Type</th>
				<th>Message</th>
				<th>Status</th>
				<th>Comments</th>
			</tr>
		</thead>
		<tbody>
			{% for complaint in complaint_list %}
				<tr>
					<td>{{ complaint.created_at }}</td>
					<td>{{ complaint.hall }}</td>
					<td>{{ complaint.type }}</td>
					<td>{{ complaint.message }}</td>
					<td>{{ complaint.status }}</td>
					<td style="text-align:center">
						<a href="{% url 'student:detail_complaint' pk=complaint.pk %}"><i class="fas fa-comments"></i></a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}