comments/urls.py
from django.urls import path
from . import views

app_name = 'comments'

urlpatterns = [
	path('create_comment/<int:pk>/', views.CommentCreateView.as_view(), name='create_comment'),
	path('list_comment/', views.CommentListView.as_view(), name='list_comment'),
	path('update_comment/<int:pk>/', views.CommentUpdateView.as_view(), name='update_comment'),
	path('delete_comment/<int:pk>/delete/', views.CommentDeleteView.as_view(), name='delete_comment')
]

ticketing/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls)
]

# Index page
urlpatterns += [
    path('', views.HomePage.as_view(), name = 'home')
]

# Django site authentication urls
urlpatterns += [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('registration.backends.default.urls'))
]

# Student urls
urlpatterns += [
    path('student/', include('student.urls'))
]

# Worker urls
urlpatterns += [
    path('worker/', include('worker.urls'))
]

# Comment urls
urlpatterns += [
    path('comments/', include('comments.urls'))
]

worker/urls.py
from django.urls import path
from . import views

app_name = 'worker'

urlpatterns = [
	path('update_status/<int:pk>/', views.UpdateStatusView.as_view(), name='update_status'),
	path('all_complaints/', views.ComplaintListView.as_view(), name='all_complaints')
]

comments/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
from student import models as complaint_model
import misaka

# Create your models here.

class Comment(models.Model):
	comment = models.ForeignKey(complaint_model.Complaint, on_delete=models.CASCADE, related_name='comments')
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author')
	created_at = models.DateTimeField(auto_now_add=True)
	message = models.TextField()
	message_html = models.TextField(editable=False)

	def save(self, *args, **kwargs):
		self.message_html = misaka.html(self.message)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.message

	class Meta:
		ordering = ['-created_at']

comments/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model
User = get_user_model()
from django.http import Http404
from django.urls import reverse_lazy
from student import models as student_models
from . import models

# Create your views here.

class CommentCreateView(LoginRequiredMixin, CreateView):
	fields = ['message']
	model = models.Comment
	template_name = 'comments/create_comment.html'

	def form_valid(self, form):
		self.object = form.save(commit=False)
		complaint = get_object_or_404(student_models.Complaint, pk=self.kwargs['pk'])
		self.object.comment = complaint
		self.object.user = self.request.user
		self.object.save()
		self.success_url = reverse_lazy('student:detail_complaint', kwargs={'pk' : self.kwargs['pk']})

		return super().form_valid(form)

class CommentListView(LoginRequiredMixin, ListView):
	model = models.Comment
	template_name = 'comments/list_comment.html'

	def get_queryset(self):
		try:
			self.user_comments = User.objects.prefetch_related('author').get(username=self.request.user.username)
		except User.DoesNotExist:
			raise Http404

		return self.user_comments.author.all()

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	fields = ['message']
	model = models.Comment
	template_name = 'comments/update_comment.html'
	success_url = reverse_lazy('comments:list_comment')

	def test_func(self):
		return self.get_object().user == self.request.user

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.save()

		return super().form_valid(form)

class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = models.Comment
	template_name = 'comments/delete_comment.html'
	success_url = reverse_lazy('comments:list_comment')

	def test_func(self):
		return self.get_object().user == self.request.user

templates/comments/create_comment.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>Create comment</h1>
	<form method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<input type="submit" class="btn btn-primary" value="Create" />
		{% endbuttons %}
	</form>
{% endblock %}

templates/comments/delete_comment.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>Delete comment for sure?</h1>
	<form method='post'>
		{% csrf_token %}
		{% buttons %}
			<input type='submit' class='btn btn-danger' value='Delete' />
			<a href="{% url 'comments:list_comment' %}" class="btn btn-success">Cancel</a>
		{% endbuttons %}
	</form>
{% endblock %}

templates/comments/list_comment.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>My comments</h1>
	<table id="table" class="table-light table-bordered display nowrap" style="width:100%">
		<thead class="alert-light">
			<tr>
				<th>Created at</th>
				<th>Complaint</th>
				<th>Message</th>
				<th>Edit/Delete</th>
			</tr>
		</thead>
		<tbody>
			{% for comment in comment_list %}
				<tr>
					<td>{{ comment.created_at }}</td>
					<td>{{ comment.comment }}</td>
					<td>{{ comment.message }}</td>
					<td style="text-align:center">
						<a href="{% url 'comments:update_comment' pk=comment.pk %}"><i class="fas fa-edit"></i></a>
						<a href="{% url 'comments:delete_comment' pk=comment.pk %}"><i class="fas fa-trash"></i></a>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

templates/comments/update_comment.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
	<h1>Update comment</h1>
	<form method='post'>
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<input type='submit' class='btn btn-danger' value='Update' />
		{% endbuttons %}
	</form>
{% endblock %}